spring:
  application:
    name: genai
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 1536
  datasource:
    url: jdbc:postgresql://localhost:5432/sherlock
    username: sherlock
    password: sherlock
server:
  port: 8081
logging:
  level:
    root: INFO
    de.bas.bodo: DEBUG
genai:
  ingestion:
    author-id: 69
    author-name: "Conan Doyle"
    chunk-size: 1000
    chunk-size-minimum: 400
    chunk-overlap: 100
    max-download-count: 20
    startup:
      enabled: true
    embedding:
      batch-size: 500
  generation:
    history-max-turns: 20
  retrieval:
    embedding-dimension: 1536
